#ifndef CONTROLLERCOMMANDS_HPP
#define CONTROLLERCOMMANDS_HPP

enum ControllerCommands{
	"A","B","X","Y","Z","START",
	"D_UP","D_DOWN","D_LEFT","D_RIGHT",
	"TRIGGER_L","TRIGGER_R",
	"MAIN_UP", "MAIN_DOWN", "MAIN_LEFT", "MAIN_RIGHT",
	"C_STICK_UP","C_STICK_DOWN","C_STICK_LEFT", "C_STICK_RIGHT"
};

#endif //CONTROLLERCOMMANDS_HPP