#ifndef CONTROLLERCOMMANDS_HPP
#define CONTROLLERCOMMANDS_HPP

enum ControllerCommands{
	A=0,B=1,X=2,Y=3,Z=4,START=5,
	D_UP=6,D_DOWN=7,D_LEFT=8,D_RIGHT=9,
	TRIGGER_L=10,TRIGGER_R=11,
};

enum StickCommands{
	MAIN=12,
	C=13
};

#endif //CONTROLLERCOMMANDS_HPP
