#ifndef CONTROLLERCOMMANDS_HPP
#define CONTROLLERCOMMANDS_HPP

enum ControllerCommands{
	A,B,X,Y,Z,START,
	D_UP,D_DOWN,D_LEFT,D_RIGHT,
	TRIGGER_L,TRIGGER_R,
};

enum StickCommands{
	MAIN,
	C
};

#endif //CONTROLLERCOMMANDS_HPP
